name: Daily Airbnb Job Matcher
on:
  schedule:
    - cron: "0 13 * * *" # 9:00 AM Toronto time
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock" # Best practice if you have a lockfile

      - name: Set up Python
        run: uv python install 3.11

      - name: Run Job Matcher
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          RESUME_CONTENT: ${{ secrets.RESUME_CONTENT }}
          GREENHOUSE_BOARD_TOKEN: ${{ secrets.GREENHOUSE_BOARD_TOKEN }}
        # 'uv run' automatically installs dependencies from pyproject.toml
        run: uv run ./main.py

      - name: Commit updated seen_jobs.json
        run: |
          git config --global user.name 'Job-Bot'
          git config --global user.email 'bot@github.com'
          git add data/seen_jobs.json
          git commit -m "Update seen jobs [automated]" || echo "No changes"
          git push