name: Daily Airbnb Job Matcher
on:
    schedule:
        - cron: "0 13 * * *" # Runs daily at 9:00 AM Toronto time (13:00 UTC)
    workflow_dispatch: # Allows you to run it manually for testing

jobs:
    run-pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run Job Matcher
              env:
                  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
              run: python main.py

            - name: Commit updated seen_jobs.json
              run: |
                  git config --global user.name 'Job-Bot'
                  git config --global user.email 'bot@github.com'
                  git add data/seen_jobs.json
                  git commit -m "Update seen jobs [automated]" || echo "No changes"
                  git push
